spring.application.name=pedidos-service

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:pedidosdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicializacion SQL automatica
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 Console habilitada para inspeccion
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de campana promocional (Parte 2)
promo.black-friday.activa=true
