CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT PRIMARY KEY,
    nombre VARCHAR(100),
    email VARCHAR(100),
    tipo_cliente VARCHAR(50),
    nit VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS productos (
    id BIGINT PRIMARY KEY,
    nombre VARCHAR(100),
    precio DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS inventario (
    producto_id BIGINT PRIMARY KEY,
    stock INT NOT NULL,
    FOREIGN KEY (producto_id) REFERENCES productos(id)
);

CREATE TABLE IF NOT EXISTS facturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    monto DOUBLE NOT NULL,
    pagada BOOLEAN NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    subtotal DOUBLE NOT NULL,
    descuento DOUBLE NOT NULL,
    impuesto DOUBLE NOT NULL,
    total DOUBLE NOT NULL,
    fecha TIMESTAMP NOT NULL,
    estado VARCHAR(50) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE TABLE IF NOT EXISTS detalle_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INT NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    FOREIGN KEY (producto_id) REFERENCES productos(id)
);
